import type { Metadata } from 'next';
import { LeftBar } from './components/LeftBar';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <LeftBar />
      {children}
    </>
  );
}
