import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';
import { LeftBar } from './components/LeftBar';
import { NextUIProvider } from './components/NextUIProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={clsx(inter.className, 'flex h-screen w-screen flex-row')}>
        <NextUIProvider>
          <LeftBar />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
